### ISSUE TITLE
设置的问题

### ISSUE THREAD

**Issue by myChinesePYL** [iamr0s/Dhizuku#1]
什么时候做设置啊.

**Comment by iamr0s** [comment]
目前还未想好设置页应该放哪些内容，或者大家需要哪些功能。

**Comment by MIt-gancm** [comment]
语言 颜色改变 能不能完成像Shizuku在终端应用中调用 因为这个新软件 所以没太多开发者愿意 调用这个软件  可以试试主动交流

**Comment by myChinesePYL** [comment]
或许可以在设置里加一个授权弹窗的设置，比如弹窗的主题(shizuku主题/默认/root主题/...)，弹窗行为(提示/允许/拒绝)，位置(通知/弹窗/小提示)，小提示位置(上/下/左/右，居中用弹窗。当选中小提示时显示)

**Comment by myChinesePYL** [comment]
还有，那个深色模式适配的不是很好，弹窗字体没适配(默认是黑色，深色模式还是黑色)

**Comment by iamr0s** [comment]
> 

Dhizuku和Shizuku不是一类应用，在部分调用上有些许交集。
至于提供类似Shizuku的rish功能，在Dhizuku应该不太能实现。
因为Dhizuku即使是设备所有者，在执行`pm install path`时会报错。只能通过代码`Context.getPackageManager().getPackageInstaller()`实现调用。

**Comment by myChinesePYL** [comment]
实现不了rish，那就把所有能用的接口写到rish里面去(doge
rish> help
pm - 软件包管理...
icebox - 冻结(icebox package_name)
...

**Comment by iamr0s** [comment]
这是一项复杂的工作，当你需要用到这些功能时，往往Shizuku更加适合你。
同时这也不是我创建Dhizuku的本来目的（系统只允许单个设备所有者，让需要所有者权限工作的应用都能间接拿到所有者权限。）

**Comment by myChinesePYL** [comment]
但我是android10华为，不想用电脑激活，麻烦，没root

**Comment by iamr0s** [comment]
你可以寻求一些已经接入[Dhizuku API](https://github.com/iamr0s/Dhizuku-API)的应用。
而不是依靠输入命令（实际上，实现你说的这种rish，等同于实现一个接入Dhizuku-API的应用）。

同时你也可以去依靠设备所有者实现的应用下，请求他们接入Dhizuku-API。

**Comment by myChinesePYL** [comment]
emm，行

**Comment by MIt-gancm** [comment]
授权确实有必要像安装狮
![IMG_20230501_102254](https://user-images.githubusercontent.com/72749591/235392741-9b4159df-7686-4de3-b199-42f458503442.jpg)
可以直接调用 来实现静默安装
