### ISSUE TITLE
希望可以自定义系统“此设备由贵单位管理”的提示

### ISSUE THREAD

**Issue by GOldX3Cheng** [iamr0s/Dhizuku#15]
希望可以自定义系统“此设备由贵单位管理”的提示

**Comment by iamr0s** [comment]
请阅读 [Dhizuku 临时文档](https://www.coolapk.com/feed/45819359?shareKey=MGQ4MDc1ZThhNjI3NjQ5MDg2MGU~&shareUid=1581760&shareFrom=com.coolapk.market_13.2.1) 中关于DAX的介绍，你会知晓一切

前往 #14 下载被DAX强制支持Dhizuku的Test DPC，它提供有这个功能
注意Test DPC有两种启动入口，请选择名称为Test DPC的入口
