### ISSUE TITLE
提供英文版本的激活教程？

### ISSUE THREAD

**Issue by deltazefiro** [iamr0s/Dhizuku#18]
您好。感谢您开发了 Dhizuku 这样优秀的程序，让我们能够便捷地在应用间共享 DeviceOwner 权限。  
我最近在自己的应用中接入了 Dhizuku API，但我在编写用户文档时发现 Dhizuku 并未提供英文版本的激活指南。（或者我漏掉了些什么没找到？）    

您是否考虑提供一个英文版本的指南呢？相信提供英文文档能够使您的应用受到更广泛的使用，而非仅限与国内。  

或许您也可以创建一个独立的文档仓库，使用 [Vuepress](https://vuepress.vuejs.org/zh/guide/) 构建静态文档网站并托管在 [GitHub Pages](https://pages.github.com/) 上。并将文档加入 Weblate，允许社区贡献翻译。

**Comment by iamr0s** [comment]
好的，我会在一段时间后开始。

其实我的本意是使用Github Discussion来发布相关的文档，这也会更加便捷的展开围绕文档的交流。
但是，这类文档不能友好的接入Weblate。

我会考虑使用Vuepress。

**Comment by iamr0s** [comment]
新增了英文文档 [Github Discussions](https://github.com/iamr0s/Dhizuku/discussions/19)。

考虑到 Discussions 含有讨论功能，且我本身不怎么熟悉Vuepress，所以先发布了 Discussions 版本的激活教程。

并在 [Dhizuku](https://github.com/iamr0s/Dhizuku) 主页增加了激活教程的链接

**Comment by deltazefiro** [comment]
非常感谢。
