### ISSUE TITLE
License 问题

### ISSUE THREAD

**Issue by tiann** [iamr0s/Dhizuku#5]
我注意到这个 library 的协议是 GPL3，这要求所有使用这个库的 APP 开源其自身代码，这实际上是不现实的。很多使用 deviceowner 的 APP 都不开源，如冰箱，太极，小黑屋。
如果你想让这个库被更多人使用，建议你更换 License 为 LGPL。
当然，这只是一个建议，我们尊重你的选择。

**Comment by iamr0s** [comment]
好的，谢谢你的建议。
但是[Dhizuku API](https://github.com/iamr0s/Dhizuku-API) 是基于MIT协议的，而Dhizuku是Dhizuku API的一个服务端实现。所以其余应用成为Dhizuku Client后的开源选择是自由的。

关于Dhizuku是协议变更为LGPL，我会仔细考虑这个问题。

**Comment by tiann** [comment]
看来是我理解错了，目前你这么处理也是没有问题的。我还以为 Dhizuku 是一个 library，集成这个 library 的任何 APP 都可以成为 server；原来它自己是一个 APP...这样也没有问题。

**Comment by iamr0s** [comment]
谢谢你的提醒，经过我的考虑，我在未来也许会将Dhizuku Server功能从Dhizuku中分离出来。
Dhizuku仅作为一个Dhizuku Server的设备所有者实现，其余应用也可以自行集成Dhizuku Server，实现他们自己的权限共享。
