### ISSUE TITLE
Allow transfer of device owner permissions.

### ISSUE THREAD

**Issue by SteveZMTstudios** [iamr0s/Dhizuku#64]
After Android 12, device owner permissions can already be transferred to other apps. Other applications, including test DPC, must obtain device owner privileges themseives to work properly, and cannot be patched with DAX modules or granted with dhizuku.

在安卓12以后，设备所有者权限已经可以被转移给其他应用程序。其中包括test dpc在内的其他应用程序必须要亲自获得device owner权限才可以正常工作,无法使用DAX模块修补或者使用dhizuku授权。

**Comment by SteveZMTstudios** [comment]
![Screenshot_2024-08-06-17-41-36-474_com.afwsamples.testdpc-edit.jpg](https://github.com/user-attachments/assets/d3e4de90-e28c-4d43-b991-59d82efbc8bc)

**Comment by SteveZMTstudios** [comment]
![Screenshot_2024-08-06-17-42-14-477_com.afwsamples.testdpc-edit.jpg](https://github.com/user-attachments/assets/91a78b00-72a6-4f1e-8e09-590499ac23a2)

**Comment by iamr0s** [comment]
DAX可以的 它的实现本就是让应用以为自己获取到了Device Owner 并通过Dhizuku接口使用dpm

**Comment by SteveZMTstudios** [comment]
> DAX可以的 它的实现本就是让应用以为自己获取到了Device Owner 并通过Dhizuku接口使用dpm

Test DPC还有一些特别的机制，比如Profile Owner ，具体情况我不清楚，但是我猜测它利用了一些只存在于Android系统的特性。

![Screenshot_2024-08-06-18-37-16-601_com.f0x1d.logfox.jpg](https://github.com/user-attachments/assets/aaf1d4d8-b8e1-4f69-b2a6-e64a9a302be9)

**Comment by iamr0s** [comment]
Has been implemented in version 2.9
