### ISSUE TITLE
求助，激活不成功卸载后如何恢复原来的设备管理员

### ISSUE THREAD

**Issue by smoile** [iamr0s/Dhizuku#7]
昨晚看到后下载安装了，激活显示是部分成功，于是就卸载了。但是发现卸载后相机被禁用了，其他是否有禁用还没有发现。
![Screenshot_20230510_073105_com huawei camera](https://github.com/iamr0s/Dhizuku/assets/46859194/6958ebde-98aa-41ad-afc3-669c871f10e6)
查看用户显示如下：
![Snipaste_2023-05-10_08-42-24](https://github.com/iamr0s/Dhizuku/assets/46859194/51c4ecbc-182f-4d3e-99e9-4575fdbfb165)

请大神们指点一二，是不是通过什么命令恢复到以往

**Comment by iamr0s** [comment]
请前往[UserService Demo](https://github.com/iamr0s/Dhizuku-API/releases)下载最新的Demo。
2.3版本新增了相机禁用功能（部分激活状态下的Dhizuku也可用）
如果可用请close the issue。
