### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [iamr0s/Dhizuku#8]
https://hosted.weblate.org/projects/dhizuku/app/#information
says LGPLv3, but
https://github.com/iamr0s/Dhizuku/blob/main/LICENSE says
GPLv3.

Also, doing "or later" helps if you want to change to AGPLv3 or GPLv4 in the future.
If it isn't "or later", it means every translator needs to agree when/if that happens.

It can be changed in https://hosted.weblate.org/settings/dhizuku/app/

**Comment by iamr0s** [comment]
sorry, my English is so bad, I didn't notice Less and General.
And I changed the license to GPLv3 or later, Is it ok?

**Comment by comradekingu** [comment]
Yes. :) It is also better to say it is GPLv3-**or-later** here on GitHub.
Now it just says GPLv3.

**Comment by Ermageeerd** [comment]
> sorry, my English is so bad, I didn't notice Less and General. And I changed the license to GPLv3 or later, Is it ok?

Unrelated, but having English as my primary language, your English is actually not half bad.

**Comment by Ermageeerd** [comment]
(yes i know this was a while ago and you likely omproved, gotta help a fellow langtage learner!)
