### ISSUE TITLE
软件故障？

### ISSUE THREAD

**Issue by Ai686Leo** [iamr0s/Dhizuku#9]
![Screenshot_20230511-201006_Shell.png](https://github.com/iamr0s/Dhizuku/assets/104388319/ca59873a-ce6f-42ce-8559-734645a24b76)

![Screenshot_20230511-201052_Pixel_启动器.png](https://github.com/iamr0s/Dhizuku/assets/104388319/70ed6795-fa08-47b3-97a0-ad5b8fef95db)

![Screenshot_20230511-201058_Pixel_启动器.png](https://github.com/iamr0s/Dhizuku/assets/104388319/8ba01269-d461-438a-acfc-f6875d6934bd)

![Screenshot_20230511-201101_Pixel_启动器.png](https://github.com/iamr0s/Dhizuku/assets/104388319/fe104f49-175b-4de7-bd36-c4288b6569d4)

bug？

**Comment by iamr0s** [comment]
需要应用主动申请
比如R安装就是点击主页的状态显示那一栏
![Screenshot_2023-05-10-23-37-50-691_com yxer packageinstalles-edit](https://github.com/iamr0s/Dhizuku/assets/41138521/185218ec-6f4f-474a-b2a1-0ce9b41968c9)
