### ISSUE TITLE
Can't activate on HyperOS

### ISSUE THREAD

**Issue by Dantoza** [iamr0s/Dhizuku#96]
So for activation of dhizuku you can't have accounts on the device. But to have USB debuging turned on you need to have a SIM card and a Xiaomi account logged in. Any way to bypass that?

**Comment by lyyh0** [comment]
用shizuku的无线调试？我没用过hyper2
我记得打开了usb调试后是可以移除小米账号的，不行也可以先给爱玩机的修改系统安全权限再让爱玩机打开
可能hyper2改了吧，我可能不能帮助到你

**Comment by Dantoza** [comment]
Yes, but you need to reboot to apply the changes, and after reboot xiaomi requires you to log in and automaticly turns off USB debugging
